version: '3'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

    networks:
      - fronend
      - auth


networks:
  fronend:
  auth:
    external:
      name: auth